### ISSUE TITLE
Create a customized link tree using HTML CSS and JavaScript.

### ISSUE THREAD

**Issue by priyamaggarwal18** [Anamika1-cpu/Hacktoberfest2023-Web-Developers#14]
Hi @Anamika1-cpu, I assume that I can contribute to this issue, so please assign this issue to me. Also, please label this issue as Hacktoberfest. I would be very grateful to you if you do so.

**Comment by Anamika1-cpu** [comment]
I have assigned it to you. Now, you can start working on it.

**Comment by priyamaggarwal18** [comment]
Okay, thanks for assigning this issue to me.
